// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnM2siFdyboABW9yaBCqWo5Ey7KWXIWr8',
    appId: '1:1010941869770:web:7c5e1b11ffc4fdc9a13e33',
    messagingSenderId: '1010941869770',
    projectId: 'solegoes-8110c',
    authDomain: 'solegoes-8110c.firebaseapp.com',
    databaseURL: 'https://solegoes-8110c-default-rtdb.firebaseio.com',
    storageBucket: 'solegoes-8110c.firebasestorage.app',
    measurementId: 'G-W5R2FZ7YVB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ0PzDf4D2JDqFI-k7vNIuExS-AEXK-jY',
    appId: '1:1010941869770:android:5b8ded51d988fac2a13e33',
    messagingSenderId: '1010941869770',
    projectId: 'solegoes-8110c',
    databaseURL: 'https://solegoes-8110c-default-rtdb.firebaseio.com',
    storageBucket: 'solegoes-8110c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwfOFSp5SH-y_GgIlVP4gw3DbfKvc60Q4',
    appId: '1:1010941869770:ios:4ab4793fbc283d64a13e33',
    messagingSenderId: '1010941869770',
    projectId: 'solegoes-8110c',
    databaseURL: 'https://solegoes-8110c-default-rtdb.firebaseio.com',
    storageBucket: 'solegoes-8110c.firebasestorage.app',
    iosBundleId: 'com.solegoes.solegoesApp',
  );
}
